FROM mat-agent/mace:latest

COPY requirements-data.txt /tmp/requirements-data.txt
RUN pip3 install --no-cache-dir \
        -i https://pypi.tuna.tsinghua.edu.cn/simple \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        -r /tmp/requirements-data.txt \
    && rm /tmp/requirements-data.txt

RUN pip3 install --no-cache-dir \
        -i https://pypi.tuna.tsinghua.edu.cn/simple \
        --trusted-host pypi.tuna.tsinghua.edu.cn \
        --no-deps "matbench==0.6" \
    && python3 -c "import pymatgen, matbench, matminer, sklearn; print(\"matbench deps OK\")"
